### ISSUE TITLE
Website Pop-Up

### ISSUE THREAD

**Issue by rapidzsimon** [rapidz/chilango#1]
Can you please create a pop-up with this graphic:

![chilango-webbanner-12-9-17_v1](https://user-images.githubusercontent.com/24432633/30338814-cedd168c-97e4-11e7-808a-ad501d83aaa4.jpg)

I think the functionality is already there, just need to include this image.

Thanks.

**Comment by rapidzsteph** [comment]
Live on the .pw site: http://chilango.rapidz.pw/

Will only appear once every 7 days - you'll have to clear your cookies if you reload and want to see it again
